### abapgit_old
GET {{baseUrl}}/sap/bc/adt/programs/programs/zabapgit_old/source/main/versions
Authorization: Basic {{user}}:{{password}}
Accept: application/atom+xml;type=feed
Cache-Control:no-cache
withCredentials:true
x-csrf-token:o-Dpt85T6fpB8JaWn0UC2w==
X-sap-adt-sessiontype:stateless

### Source
GET {{baseUrl}}/sap/bc/adt/programs/programs/zabapgit_old/source/main
Authorization: Basic {{user}}:{{password}}
Cache-Control:no-cache
Accept: text/plain
